phenom4n4n/phen-cogs

- linkquoter/info.json
- linkquoter/linkquoter.py
- webhook/__init__.py
- webhook/webhook.py
Pull request to follow the issue that was created.
> Linkquoter rewrite

- roleutils/converters.py
- roleutils/info.json
- roleutils/roles.py
- roleutils/roleutils.py
Adds targeter commands under `[p]role target`. Waiting on my [Targeter API PR](https://github.com/NeuroAssassin/Toxic-Cogs/pull/35) to be accepted to merge this.
> [roleutils] targeter

- baron/baron.py
You can remove the commented line if merged as it's just for note. May want to break the logic up too, idk. 
But good to check if that websocket is already ratelimited before calling to chunk
> check for websocket ratelimit

- tags/adapters.py
- tags/converters.py
- tags/info.json
- tags/objects.py
- tags/tags.py
- webhook/webhook.py
Adds support for global tags, tag invocation in DM's, and alias to tag cog migration.
> Global Tags

- roleutils/roles.py
Added 2 new commands:
`[p]role addmulti`: add a role to multiple users
`[p]role removemulti`: removes a role from multiple users
> [RoleUtils] addmulti and removemulti commands

- slashtags/slashtags.py
*not slashinjector, but whatever*
> [slashwhatever] fix cog_before_invoke

- webhook/converters.py
- webhook/errors.py
- webhook/session.py
- webhook/utils.py
- webhook/webhook.py
This PR adds:
- better session support through use of a listener. it also lets sessions go longer than 2 minutes and persist until cog reload
- rewrites link handling to also cache links and ratelimiting
> [Webhook] just some updates

- embedutils/commands.py
- embedutils/converters.py
- embedutils/embed.py
- embedutils/errors.py
This PR rewrites and adds new features to the EmbedUtils cog.
Checklist:
> [EmbedUtils] Rewrite

- prefix/prefix.py
I haven't tested this but there's no reason it shouldn't work ¯\_(ツ)_/¯
> Return in [p]prefix remove

- slashtags/commands.py
> Add missing `ctx` to command calls

- slashtags/http/models.py
- slashtags/mixins/processor.py
I haven't tested this change or anything so 🤞
> [SlashTags] Use `create_dm` if channel data is not present

- aki/aki.py
- aki/menus.py
- connect4/__init__.py
- connect4/connect4.py
- connect4/core.py
- connect4/info.json
- connect4/menus.py
- slashtags/http/httpclient.py
- slashtags/http/models.py
- slashtags/testing/button_menus.py
Adds button support to Aki and Connect4 and edits some stuff in SlashTags for buttons to work better.
> [buttons] 

- slashtags/converters.py
- slashtags/core.py
- slashtags/mixins/commands.py
- slashtags/mixins/processor.py
- tags/commands.py
- tags/converters.py
- tags/core.py
- tags/errors.py
Adds support to add tags via Pastebin.
Also adds the override and cooldown block to slashtags.
> [tags/slashtags] pastebin

- slashtags/mixins/commands.py
Some docstring links were linking to the wrong page, causing 404s
> [SlashTags] Fix a few docstring links

- lock/lock.py
> Lock examples

- slashtags/core.py
- slashtags/mixins/commands.py
Fixes: https://sentry.io/share/issue/0c948eef3eec4e17a60d90335217da61/
> [SlashTags] Convert type response to lowercase

- connect4/core.py
it was checking only 6 wide (height) not 7 wide (width) when looking for a 4 in a row from top-left to bottom-right
> fixes not finding 4 in a row in last column

- disboardreminder/disboardreminder.py
- embedutils/embed.py
DisboardReminder: Errored but it seems everything that uses member config has been removed so there's no need for it
https://sentry.io/share/issue/3465ab95b593463ba39f9d86b07a36f0/
EmbedUtils: Not tested but it should work looking at the way data is stored in config
https://sentry.io/share/issue/e34e9de4b4914cdbb13454b57c5454bf/
> Fix Data Deletion

- simplecalculator/calculator.py
This shows the output in a properly formatted way with comma notation.
> [simplecalculator] Formatted output.

- linkquoter/converters.py
per discussion in the 3rd party server
> [linkquoter] Use get_guild + get_channel over bot.get_channel

- tags/processor.py
basically this PR fixes this issue
> [Tags] bug fix on argument loop on invoketag

- tags/processor.py
> [tags] Ahh sorry for another PR, didn't notice earlier but I did an oopsie in the last one so

- aki/aki.py
async with typing, ctx has no 'trigger_typing' attribute
> Update aki.py "async with ctx.typing()"

- baron/baron.py
it should be typing() for dpy2
> it should be typing() for dpy2

- baron/baron.py
AttributeError: 'NoneType' object has no attribute 'url'
> sometimes servers dont have icon
